package internal

const (
	OP_ADD = 21
	OP_ADD_IMM = 11
	OP_SUB = 22
	OP_SUB_IMM = 12
	OP_MUL = 23
	OP_MUL_IMM = 13
	OP_CMP = 24
	OP_CMP_IMM = 14
	OP_TX_DIGIT = 25
	OP_TX_DIGIT_IMM = 15
	OP_TX_FIELD = 26
	OP_TX_FIELD_IMM = 16
	OP_TX_RECORD = 31
	OP_BRANCH = 49
	OP_BRANCH_NO_FLAG = 44
	OP_BRANCH_NO_RECORD_MARK = 45
	OP_BRANCH_ON_DIGIT = 43
	OP_BRANCH_IND = 46
	OP_BRANCH_NO_IND = 47
	OP_BRANCH_AND_TX = 27
	OP_BRANCH_AND_TX_IMM = 17
	OP_BRANCH_BACK = 42
	OP_RD_NUM = 36
	OP_WR_NUM = 38
	OP_DUMP_NUM = 35
	OP_RD_ALNUM = 37
	OP_WR_ALNUM = 39
	OP_CTRL = 34
	OP_SET_FLAG = 32
	OP_CLEAR_FLAG = 33
	OP_HALT = 48
	OP_NOP = 41
)

const OpCodeNames map[int]string {
	OP_ADD: "A",
	OP_ADD_IMM: "AM",
	OP_SUB: "S",
	OP_SUB_IMM: "SM",
	OP_MUL : "M",
	OP_MUL_IMM : "MM",
	OP_CMP : "C",
	OP_CMP_IMM : "CM",
	OP_TX_DIGIT : "TD",
	OP_TX_DIGIT_IMM : "TDM",
	OP_TX_FIELD : "TF",
	OP_TX_FIELD_IMM : "TFM",
	OP_TX_RECORD : "TR",
	OP_BRANCH : "B",
	OP_BRANCH_NO_FLAG : "BNF",
	OP_BRANCH_NO_RECORD_MARK : "BNR",
	OP_BRANCH_ON_DIGIT : "BD",
	OP_BRANCH_IND : "BI",
	OP_BRANCH_NO_IND : "BNI",
	OP_BRANCH_AND_TX : "BT",
	OP_BRANCH_AND_TX_IMM : "BTM",
	OP_BRANCH_BACK : "BB",
	OP_RD_NUM : "RN",
	OP_WR_NUM : "WN",
	OP_DUMP_NUM : "DN",
	OP_RD_ALNUM : "RA",
	OP_WR_ALNUM : "WA",
	OP_CTRL : "K",
	OP_SET_FLAG : "S",
	OP_CLEAR_FLAG : "CF",
	OP_HALT : "H",
	OP_NOP : "NOP",
}